import { createSlice } from '@reduxjs/toolkit';

const researchPublicationAndProjectArrTest = [
  // - id serial primary_key
  // - category_name text
  // - img_file_path text
  // - view_count integer
  // - title text
  // - author_img_file_path text
  // - author_name text
  // - link text
  {
    id: 1,
    category_name: 'Area-BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 2,
    category_name: 'Area-BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 3,
    category_name: 'Area-BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 4,
    category_name: 'Area-BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 5,
    category_name: 'Area-BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 6,
    category_name: 'Area-BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 7,
    category_name: 'Area-BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 8,
    category_name: 'Area-BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 9,
    category_name: 'Area-BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 10,
    category_name: 'BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 11,
    category_name: 'BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 12,
    category_name: 'BCM',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 13,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 14,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 15,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 16,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 17,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 18,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 19,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 20,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 21,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 22,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 23,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 24,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 25,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
  {
    id: 26,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Business Continuity Management toward Public Healthcare Systems during the Disaster',
    author_img_file_path: '../../images/profile.png',
    author_name: 'David Beckham',
    link: 'https://google.com',
  },
  {
    id: 27,
    category_name: 'Disaster',
    img_file_path: '../../images/home-card.png',
    view_count: 100,
    title: 'Area-Business Continuity Management',
    author_img_file_path: '../../images/profile.png',
    author_name: 'Michele Morrone',
    link: 'https://google.com',
  },
];

const resourceSlice = createSlice({
  name: 'resource',
  initialState: { researchPublicationArr: [], projectArr: [] },
  reducers: {
    setResearchPublicationArr(state, action) {
      state.researchPublicationArr = action.payload || researchPublicationAndProjectArrTest;
    },
    setProjectArr(state, action) {
      state.projectArr = action.payload || researchPublicationAndProjectArrTest;
    },
  },
});

export const resourceActions = resourceSlice.actions;
export default resourceSlice.reducer;
